### ISSUE TITLE
Fix imports on new material-ui versions

### ISSUE THREAD

**Issue by Frioo** [TeamWertarbyte/material-ui-bottom-sheet#15]
```
./node_modules/material-ui-bottom-sheet/lib/components/BottomSheet/BottomSheet.js
Module not found: Can't resolve 'material-ui/Paper'
```
The components are now in `/core`
```js
import { Paper } from "@material-ui/core";
```

**Comment by leMaik** [comment]
This project isn't available for Material-UI >= 1.0.0 since it already ships with a temporary swipeable drawer that can be attached to the bottom. That replaces the bottom sheet.

Have a look into the Material-UI docs for a demo: https://material-ui.com/components/drawers/#temporary-drawer (click the "open bottom" button)
